"""ITD (Idaho Transportation Department) bid-abstract PDF parser.

Source: ``https://apps.itd.idaho.gov/apps/contractors/abst{key}.pdf``
indexed from ``https://itd.idaho.gov/contractor-bidding/``. ITD
publishes "bid abstracts" — the post-bid award summary for each
contract let — as PDFs generated by AASHTOWare Project™. These are
public records under Idaho transparency mandates, robots-permitted
(``itd.idaho.gov/robots.txt`` only disallows ``/wp-admin/``), and
ship as native PDFs with a clean text layer (no OCR needed).

Parser scope: page 1 only. Page 1 is the AASHTOWare "Vendor Ranking"
single-page summary with everything ``ParsedBidPost`` needs. Pages 2+
are line-item detail used by v1.5b for unit-price analytics — not
this slice's concern.

Two templates exist in the wild (caught during fixture capture
2026-04-29):

  * ``aashtoware_v1`` — page 1 contains both "AASHTOWare Project"
    and "Vendor Ranking" anchors. **Parser target.** Example fixture:
    ``tests/fixtures/itd/abst25183.pdf``.
  * ``itd_legacy``    — page 1 starts "Official Bid Abstracts for
    Bid Opening …" and goes straight into per-line-item bidder
    pricing without a per-vendor summary. **Parser returns None.**
    The pipeline's fail-soft policy logs a warn-and-skip; v1.5b's
    backfill worker can target these via the ``template_version``
    field in ``MANIFEST.json``. Example: ``abst23614.pdf``.

Anchor constants are documented module-level so a future template
break can be debugged by diffing new HTML against the named
fixtures. Whenever a new anchor is needed, add it here with the
exemplar fixture filename.
"""
from __future__ import annotations

import io
import logging
import re
from datetime import date, datetime
from typing import Any

import pdfplumber

from urllib.parse import urljoin, urlparse

from app.services.market_intel.scrapers._base import (
    FetchedDocument,
    ParsedBidder,
    ParsedBidPost,
    PostParser,
)

log = logging.getLogger("fieldbridge.market_intel.itd")


# ---------------------------------------------------------------------------
# Pipeline-facing constants. Used by ``services.market_intel.pipeline``
# to orchestrate ITD ingest. Centralized here so a future ITD URL
# change is a one-file edit.

INDEX_URL = "https://itd.idaho.gov/contractor-bidding/"
SOURCE_NETWORK = "state_dot_itd"

# Parse-result status codes returned by ``parse_bid_abstract_full``.
# The pipeline maps these onto its counters dict for n8n logging.
PARSE_OK = "ok"
PARSE_LEGACY_TEMPLATE = "legacy_template"
PARSE_UNKNOWN_TEMPLATE = "unknown_template"
PARSE_CORRUPT_PDF = "corrupt_pdf"
PARSE_MISSING_FIELDS = "missing_required_fields"
PARSE_NO_VENDORS = "no_vendor_rows"
PARSE_EMPTY_INPUT = "empty_input"


# ---------------------------------------------------------------------------
# Module-level anchors. When parsing breaks against new ITD output, the
# canonical debug step is: ``diff <new pdf page 1 text> <fixture>``
# against the listed fixture filename and update the relevant constant.

# Template detection. Both substrings must appear on page 1.
# Exemplar: tests/fixtures/itd/abst25183.pdf
ANCHOR_AASHTOWARE = "AASHTOWare Project"
ANCHOR_VENDOR_RANKING = "Vendor Ranking"

# Legacy template signal (parser returns None). The parser does not
# attempt to extract from this layout; v1.5b backfill addresses it.
# Exemplar: tests/fixtures/itd/abst23614.pdf
ANCHOR_LEGACY = "Official Bid Abstracts"

# Field-extraction regexes. Tested against all 22 v1 fixtures captured
# 2026-04-29; if a future capture breaks one, add the failing fixture
# filename in a comment here and update the pattern.
RE_CONTRACT_ID = re.compile(r"Contract ID:\s+(\S+)")
RE_LETTING_DATE = re.compile(
    # "April 14, 2026 2:00PM" or "March 17, 2026 2:00pm" — matched on
    # the date portion, AM/PM time discarded.
    r"Letting Date:\s+([A-Z][a-z]+\s+\d{1,2},\s+\d{4})"
)
RE_COUNTIES = re.compile(
    # "Counties: Bingham" or "Counties: Twin Falls" — span until next
    # known field anchor on the same line.
    r"Counties:\s+(.+?)(?=\s+District\(s\):|\s*$)",
    re.MULTILINE,
)
RE_CONTRACT_DESCRIPTION = re.compile(
    # "Contract Description: I-15, RIVERTON ROAD BRIDGE" — span until
    # next field anchor.
    r"Contract Description:\s+(.+?)(?=\s+Project\(s\):|\s*$)",
    re.MULTILINE,
)

# Vendor-row pattern. Anchored to start-of-line. The vendor_id format
# observed across all v1 fixtures is one uppercase letter followed by
# exactly four digits (e.g. C0029, S0357, B0261). The "Irregular Bid"
# annotation, when present, sits between vendor_id and the vendor name
# and is stripped into the bidder's ``notes`` field.
#
# Exemplar with "Irregular Bid": tests/fixtures/itd/abst25183.pdf
# Exemplar with multi-line vendor name continuation:
#   tests/fixtures/itd/abst22215.pdf  (STAKER & PARSON COMPANIES dba
#   IDAHO MATERIALS & CONSTRUCTION wraps to a continuation line)
RE_VENDOR_ROW = re.compile(
    r"^\s*(\d+)\s+([A-Z]\d{4})\s+(?:(Irregular Bid)\s+)?(.+?)\s+\$([\d,]+\.\d{2})\s+([\d.]+)%",
    re.MULTILINE,
)

# Header line that delineates the start of the vendor ranking table.
# Used to find where vendor rows begin so we can grab continuation
# lines (vendor names that wrap) immediately after each matched row.
RE_TABLE_HEADER = re.compile(r"Rank\s+Vendor ID/Name\s+Total Bid")


# ---------------------------------------------------------------------------
# Public API: pure function form.

def parse_bid_abstract(pdf_bytes: bytes, source_url: str) -> ParsedBidPost | None:
    """Parse one ITD AASHTOWare ``aashtoware_v1`` bid abstract PDF.

    Returns ``None`` for:
      * empty / corrupt / non-PDF bytes
      * legacy "Official Bid Abstracts" template (slice-2 out of scope)
      * any template the parser doesn't recognize

    Never raises on malformed input — the pipeline's fail-soft policy
    expects a clean None.

    Convenience wrapper around ``parse_bid_abstract_full`` that drops
    the status code. Pipeline consumers should call ``_full`` directly
    so they can distinguish legacy-template skips from parse errors.
    """
    post, _ = parse_bid_abstract_full(pdf_bytes, source_url)
    return post


def parse_bid_abstract_full(
    pdf_bytes: bytes,
    source_url: str,
) -> tuple[ParsedBidPost | None, str]:
    """Parse a bid abstract PDF and return (post|None, status_code).

    Status codes (module-level constants ``PARSE_*``):

      * ``PARSE_OK``                 — successful parse
      * ``PARSE_LEGACY_TEMPLATE``    — older "Official Bid Abstracts"
                                       layout; v1.5b backfill target
      * ``PARSE_UNKNOWN_TEMPLATE``   — recognized neither v1 nor legacy
      * ``PARSE_CORRUPT_PDF``        — pdfplumber failed (bad bytes)
      * ``PARSE_EMPTY_INPUT``        — empty/missing pdf_bytes
      * ``PARSE_MISSING_FIELDS``     — v1 layout but required fields
                                       absent (Contract ID etc.)
      * ``PARSE_NO_VENDORS``         — v1 layout but vendor table empty

    The pipeline's counters dict reads the status code to distinguish
    ``skipped_legacy_template`` from ``skipped_parse_error`` for n8n
    logging.
    """
    if not pdf_bytes:
        return None, PARSE_EMPTY_INPUT

    try:
        with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:
            if not pdf.pages:
                return None, PARSE_CORRUPT_PDF
            page1_text = pdf.pages[0].extract_text() or ""
    except Exception as exc:
        log.warning("itd: pdfplumber failed on %s: %s", source_url, exc)
        return None, PARSE_CORRUPT_PDF

    return _parse_v1_text_full(page1_text, source_url=source_url)


def _parse_v1_text(text: str, *, source_url: str) -> ParsedBidPost | None:
    """Convenience wrapper around ``_parse_v1_text_full``."""
    post, _ = _parse_v1_text_full(text, source_url=source_url)
    return post


def _parse_v1_text_full(
    text: str, *, source_url: str,
) -> tuple[ParsedBidPost | None, str]:
    """The text-only parser core with status-code return.

    Public-ish for unit testing without needing a real PDF — pass a
    string that imitates the page-1 text of an aashtoware_v1 abstract.
    """
    if not text:
        return None, PARSE_EMPTY_INPUT

    # Template gate. Both anchors required.
    if ANCHOR_AASHTOWARE not in text or ANCHOR_VENDOR_RANKING not in text:
        if ANCHOR_LEGACY in text:
            log.info("itd: legacy template at %s — skip-with-warn", source_url)
            return None, PARSE_LEGACY_TEMPLATE
        log.warning("itd: unrecognized template at %s", source_url)
        return None, PARSE_UNKNOWN_TEMPLATE

    # Required fields. If any of these are missing, the PDF is
    # structurally too damaged to trust — return None.
    contract_id = _first_group(RE_CONTRACT_ID, text)
    contract_desc = _first_group(RE_CONTRACT_DESCRIPTION, text)
    letting_date_str = _first_group(RE_LETTING_DATE, text)

    if not contract_id or not contract_desc or not letting_date_str:
        log.warning(
            "itd: required fields missing at %s "
            "(contract_id=%r, desc=%r, letting=%r)",
            source_url, contract_id, contract_desc, letting_date_str,
        )
        return None, PARSE_MISSING_FIELDS

    bid_open_date = _parse_letting_date(letting_date_str)
    counties = _first_group(RE_COUNTIES, text) or None

    bidders = _parse_vendor_rows(text)
    if not bidders:
        log.warning("itd: no vendor rows parsed at %s", source_url)
        return None, PARSE_NO_VENDORS

    post = ParsedBidPost(
        source_url=source_url,
        source_network=SOURCE_NETWORK,
        source_state="ID",
        project_title=contract_desc.strip(),
        project_owner="Idaho Transportation Department",
        work_scope=contract_desc.strip(),
        solicitation_id=contract_id,
        bid_open_date=bid_open_date,
        bid_status="awarded",  # bid abstracts publish post-award
        location_city=None,
        location_county=counties.strip() if counties else None,
        location_state="ID",
        bidders=tuple(bidders),
    )
    return post, PARSE_OK


def _first_group(pattern: re.Pattern[str], text: str) -> str | None:
    m = pattern.search(text)
    return m.group(1).strip() if m else None


def _parse_letting_date(s: str) -> date | None:
    """Parse 'April 14, 2026' style. Returns None on bad input."""
    try:
        return datetime.strptime(s.strip(), "%B %d, %Y").date()
    except ValueError:
        return None


def _parse_vendor_rows(text: str) -> list[ParsedBidder]:
    """Extract vendor ranking rows from page-1 text.

    Each row is captured by ``RE_VENDOR_ROW``. Continuation lines
    (vendor names that wrap to a second line) are appended onto the
    previous bidder's name when the line between two row-matches has
    no ``$`` amount — a heuristic that's reliable because page 1 has
    no other content between vendor rows.
    """
    matches = list(RE_VENDOR_ROW.finditer(text))
    if not matches:
        return []

    out: list[ParsedBidder] = []
    for i, m in enumerate(matches):
        rank = int(m.group(1))
        vendor_id = m.group(2)
        irregular = m.group(3)  # 'Irregular Bid' or None
        vendor_name = m.group(4).strip()
        amount_str = m.group(5).replace(",", "")
        bid_amount = float(amount_str)

        # Continuation-line glue. Look at lines BETWEEN this row's match
        # and the next row's match (or end-of-text). Any line lacking
        # a "$<digits>" amount is treated as a wrap-text continuation
        # of this vendor's name.
        next_start = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        gap = text[m.end():next_start]
        for line in gap.splitlines():
            line = line.strip()
            if not line:
                continue
            if "$" in line and re.search(r"\$\d", line):
                # Has a price — must be the next vendor's row already
                # (handled by next iteration), or unrelated content.
                # Stop accumulating continuation.
                break
            # Pure text line → append to vendor name.
            vendor_name = f"{vendor_name} {line}".strip()

        out.append(
            ParsedBidder(
                contractor_name=vendor_name,
                vendor_id=vendor_id,
                bid_amount=bid_amount,
                rank=rank,
                is_low_bidder=(rank == 1),
                # ITD bid abstracts publish the awarded bidder; rank 1
                # is the awarded bidder UNLESS marked Irregular (then
                # the next eligible bidder may be the actual awardee,
                # but the abstract doesn't disambiguate at this level).
                # We mark rank 1 as awarded; downstream review handles
                # irregular cases. notes captures the flag for audit.
                is_awarded=(rank == 1 and irregular is None),
                notes=irregular,
            )
        )
    return out


# ---------------------------------------------------------------------------
# URL discovery (index page → list of abstract PDF URLs)

# Match an ITD abstract PDF URL: ``.../abst{key}.pdf``. The key is
# alphanumeric (digits for typical projects, letters for proposals
# like B200526). Trailing path before the filename varies; we don't
# anchor on the host so the same regex works against any captured
# index-page HTML.
RE_ABSTRACT_HREF = re.compile(r"/abst[^/]+?\.pdf\b", re.IGNORECASE)

# Anything matching these suffixes is a known non-bid-abstract document
# inadvertently named ``abst*.pdf``. Empty for now; populate as known
# false-positives are discovered.
ABSTRACT_URL_BLOCKLIST: tuple[str, ...] = ()


def discover_idaho_abstract_urls(
    index_html: str,
    *,
    base_url: str = INDEX_URL,
    limit: int | None = None,
) -> list[str]:
    """Pure function: extract bid-abstract PDF URLs from index-page HTML.

    Returns absolute https:// URLs in DOM order (presumed
    newest-first by ITD's listing convention). Used by both the
    pipeline and the capture script.

    Filters:

      * URL ends with ``.pdf``
      * Filename starts with ``abst`` (case-insensitive)
      * URL not present in ``ABSTRACT_URL_BLOCKLIST``
      * scheme is ``https`` (relative hrefs get joined against
        ``base_url`` to absolutize)

    Duplicates are deduplicated in DOM order. ``limit`` caps the return
    list size; ``None`` means no cap.
    """
    # Local import to keep test surface tight — bs4 is heavy.
    from bs4 import BeautifulSoup

    soup = BeautifulSoup(index_html, "lxml")
    seen: set[str] = set()
    out: list[str] = []
    for a in soup.find_all("a", href=True):
        href = a["href"]
        if not RE_ABSTRACT_HREF.search(href):
            continue
        absolute = urljoin(base_url, href)
        parsed = urlparse(absolute)
        if parsed.scheme != "https":
            continue
        if absolute in ABSTRACT_URL_BLOCKLIST:
            continue
        if absolute in seen:
            continue
        seen.add(absolute)
        out.append(absolute)
        if limit is not None and len(out) >= limit:
            break
    return out


# ---------------------------------------------------------------------------
# PostParser ABC adapter

class ITDBidAbstractParser(PostParser):
    """PostParser implementation for ITD bid-abstract PDFs.

    The Pipeline orchestrator (slice 4) holds a single ``ITDBidAbstractParser``
    instance and calls ``.parse(doc)`` on each fetched document.
    """

    SOURCE_NETWORK = "state_dot_itd"

    def parse(self, doc: FetchedDocument) -> ParsedBidPost | None:
        return parse_bid_abstract(doc.content, source_url=doc.url)
