"""
LLM insight cache — one row per (tenant, module) Claude-generated payload.

The Phase-6 ``GET /api/<module>/recommendations`` endpoints compute Claude
output once and reuse it for ``DEFAULT_TTL_HOURS`` (currently 6h). Lookup
is by ``(tenant_id, module)``; rows are upserted on regeneration so we
keep at most one cached payload per slot.

The actual JSON shape lives in ``app.core.llm.InsightResponse`` —
``payload_json`` here is the validated JSON from that pydantic model
serialized via ``model_dump_json``. We keep the storage column
type-loose so the cache survives shape evolutions.

``revision_token`` is a content hash of the data context that was fed
to the LLM. The insights service compares it on read; if the current
context hashes to a different value, the cache is treated as stale
even if it hasn't expired. That keeps users from staring at LLM advice
that's lagging the underlying numbers by hours.
"""
from __future__ import annotations

import uuid
from datetime import datetime, timedelta, timezone

from sqlalchemy import (
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


# Cache TTL — public constant so the insights service and tests can use it.
DEFAULT_TTL_HOURS = 6


class LlmInsight(Base):
    __tablename__ = "llm_insights"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4()),
    )
    tenant_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # Slug of the module that produced this payload — e.g. "equipment",
    # "vendors". Matches the ``module`` arg passed into
    # ``app.core.llm.generate_insight``.
    module: Mapped[str] = mapped_column(String(60), nullable=False)

    # Hash of the data context that was fed to the LLM. Used to detect
    # "stale-but-not-expired" cache entries.
    revision_token: Mapped[str] = mapped_column(String(64), nullable=False)

    # The serialized ``InsightResponse``. Kept as TEXT (not JSON column)
    # for SQLite compatibility — Postgres still treats it as text.
    payload_json: Mapped[str] = mapped_column(Text, nullable=False)

    # Token + cost mirror so admins can watch Phase-6 spend without
    # joining ``usage_events``. Optional — populated when the insight
    # was generated by a real LLM call (not a stub).
    input_tokens: Mapped[int] = mapped_column(Integer, default=0)
    output_tokens: Mapped[int] = mapped_column(Integer, default=0)
    model: Mapped[str] = mapped_column(String(60), default="")

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        index=True,
    )
    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc)
        + timedelta(hours=DEFAULT_TTL_HOURS),
        nullable=False,
        index=True,
    )

    tenant: Mapped["Tenant"] = relationship(  # noqa: F821
        "Tenant", lazy="selectin",
    )

    __table_args__ = (
        # One cached payload per (tenant, module). Upsert on regeneration.
        UniqueConstraint("tenant_id", "module", name="uq_llm_insights_tenant_module"),
        # Composite index for the common (tenant, module) lookup. The
        # per-column ``index=True`` on ``tenant_id`` already covers the
        # tenant-only case, and ``expires_at`` gets its own auto-index
        # from ``index=True`` on the column itself — don't redeclare
        # those here or SQLite raises "index already exists" on
        # create_all.
        Index("ix_llm_insights_tenant_module", "tenant_id", "module"),
    )

    def is_fresh(
        self,
        revision_token: str,
        *,
        now: datetime | None = None,
    ) -> bool:
        """True if this row is non-expired AND the context hash matches."""
        now = now or datetime.now(timezone.utc)
        # SQLite returns naive datetimes; normalize for comparison.
        expires_at = self.expires_at
        if expires_at.tzinfo is None:
            expires_at = expires_at.replace(tzinfo=timezone.utc)
        if expires_at <= now:
            return False
        return self.revision_token == revision_token


# --------------------------------------------------------------------------- #
# Opus-4 pricing — per million tokens.                                         #
# Update in one place when Anthropic refreshes pricing.                        #
# --------------------------------------------------------------------------- #

OPUS_INPUT_PRICE = 15.00
OPUS_OUTPUT_PRICE = 75.00
OPUS_CACHE_READ_PRICE = 1.50
OPUS_CACHE_WRITE_PRICE = 18.75


def calculate_opus_cost(
    input_tokens: int,
    output_tokens: int,
    cache_read_tokens: int = 0,
    cache_write_tokens: int = 0,
) -> float:
    """USD cost for a Claude Opus 4 API call."""
    cost = (
        (input_tokens / 1_000_000) * OPUS_INPUT_PRICE
        + (output_tokens / 1_000_000) * OPUS_OUTPUT_PRICE
        + (cache_read_tokens / 1_000_000) * OPUS_CACHE_READ_PRICE
        + (cache_write_tokens / 1_000_000) * OPUS_CACHE_WRITE_PRICE
    )
    return round(cost, 6)
